version: '3.4'

services:
  messageapi:
    image: messageapi
    build:
      context: ../MessageService.Api
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=messagedb;Username=postgres;Password=postgres

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messagedb
    ports:
      - "5432:5432"
